version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-aws-services
    ports:
      - "4566:4566"
    environment:
      # Enable AWS services: S3 and Secrets Manager
      - SERVICES=s3,secretsmanager
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      # Persistence for data across restarts
      - PERSISTENCE=1
    volumes:
      # Mount a volume for persistence
      - "./localstack-data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
